### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by zimbatm** [nix-community/linuxkit-builder#3]
@grahamc mentioned that developers tend to assume that it's related to Docker due to the name.

Looking for a brain dump of ideas, one comment per name:

**Comment by zimbatm** [comment]
Nix for Mac

**Comment by zimbatm** [comment]
How about `linuxkit-nix` or LinuxKit Nix.

This would follow the pattern of the other LinuxKit sub-projects as listed at https://github.com/linuxkit/linuxkit#subprojects

**Comment by toffaletti** [comment]
besides the naming issue, the readme jumps into installation and other details without ever saying what this thing even does.
